### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/strongmind-challenge#1]
# Motivation
We want to set up the project dependencies.

# Tasks
- [x] Use React Boilerplate.
- [x] Import all dependencies.
- [x] Get a simple example running locally.
- [x] Be able to run locally.
- [x] Be able to host on the cloud.
